gameDJ/gameDJ/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('infinity.urls'))
]

gameDJ/infinity/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'infinity'


urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login_f, name='login_f'),
    path('logout/', views.user_logout, name='logout'),
    path('dashboard/', views.battle_view, name='dashboard'),
    path('end_game/', views.end_game, name='end_game'),
    path('rating/', views.leaderboard, name='rating'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gameDJ/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{% block title %}Infinity{% endblock %}</title>
    <!-- Подключение Bootstrap через CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'infinity:home' %}"><font color="purple"><b>Infinity</b></font></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active gradient-text" aria-current="page" href="{% url 'infinity:home' %}">Главная</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link gradient-text" href="{% url 'infinity:dashboard' %}">Игра</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link gradient-text" href="{% url 'infinity:rating' %}">Рейтинг</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link gradient-text" href="{% url 'infinity:logout' %}" >Выйти</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link gradient-text" href="{% url 'infinity:login_f' %}" >Вход</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link gradient-text" href="{% url 'infinity:register' %}">Регистрация</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container mt-5">
        {% block content %}
        {% endblock %}
    </div>
    <!-- Подключение JS Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

gameDJ/templates/dashboard.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <header class="header">
        <h1>Начнём же бесконечный бой!</h1>
        <p>Уровень {{ level }}</p>
    </header>
</head>


<body>
<main class="battle-container">
    <form method="post">
    {% csrf_token %}
    <input type="hidden" id="player_attack" name="player_attack">
    <input type="hidden" id="player_def" name="player_def">
    <div class="battle-area">
        <div class="player">
            <h3>{{ username }}!</h3>
            <p>Ваше HP: {{ player_hp }} | Scores: {{ player_scores }}</p>
            <img src="/media/{{ hero_img }}" class="hero_img">
            <div id="player_def_buttons">  <h4>Защищать:</h4>
                <button type="button" class="player-button" value="голова">Голова</button>
                <button type="button" class="player-button" value="торс">Торс</button>
                <button type="button" class="player-button" value="ноги">Ноги</button>
            </div>
        </div>

        <div class="result_desc">
            <button id="confirm_button" disabled>Подтвердить</button>
            {% if result %}
                <h4>Результат раунда:</h4>
                <p>Ваши действия:</p> <p><font color="blue">защита-{{ player_def }}</font> | <font color="red">атака-{{ player_attack }}</font></p>
                <p>Действия врага:</p> <p></font> <font color="red">атака-{{ enemy_attack }}</font> | <font color="blue">защита-{{ enemy_def }}</font></p>

                <h3>{{ result }}</h3>
            {% endif %}
        </div>

        <div class="enemy">
            <h3>{{ enemy }}!</h3>
            <p>HP врага: {{ enemy_hp }}</p>
            <img src="/media/{{ monster_image }}" alt="{{ enemy }}" class="monster-image" usemap="#attack-map">
            <div id="player_attack_buttons"> <h4>Атаковать:</h4>
                <button type="button" class="player-button" value="голова">Голова</button>
                <button type="button" class="player-button" value="Торс">Торс</button>
                <button type="button" class="player-button" value="ноги">Ноги</button>
            </div>
        </div>
    </div>
    </form>
</main>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const playerAttackButtons = document.querySelectorAll('#player_attack_buttons .player-button');
        const playerDefButtons = document.querySelectorAll('#player_def_buttons .player-button');
        const playerAttackInput = document.getElementById('player_attack');
        const playerDefInput = document.getElementById('player_def');
        const confirmButton = document.getElementById('confirm_button');

        function checkSelection() {
            if (playerAttackInput.value && playerDefInput.value) {
                confirmButton.disabled = false; // Разблокировать кнопку
            } else {
                confirmButton.disabled = true; // Заблокировать кнопку
            }
        }

        function handleButtonClick(buttons, targetInput) {
                buttons.forEach(button => {
                    button.addEventListener('click', function () {
                        buttons.forEach(b => b.disabled = false); // Разблокируем все кнопки
                        button.disabled = true; // Блокируем текущую
                        targetInput.value = this.value;
                        checkSelection(); // Проверить, можно ли разблокировать кнопку
                    });
            });
        }

        handleButtonClick(playerAttackButtons, playerAttackInput);
        handleButtonClick(playerDefButtons, playerDefInput);

        checkSelection();
    });
</script>

<a href="{% url 'infinity:end_game' %}" class="end_btn">Сбросить результат</a>


    <div class="modal fade" id="enemyDefeatedModal" tabindex="-1" aria-labelledby="enemyDefeatedModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="enemyDefeatedModalLabel">{{ now_enemy }} побеждён!</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Поздравляем, {{ now_enemy }} повержен!
                    <p>Ваши очки + 100</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Ура</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="playerDefeatedModal" tabindex="-1" aria-labelledby="playerDefeatedModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="playerDefeatedModalLabel">Вас победил {{ now_enemy }}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">Закрыть</button>
                </div>
                <div class="modal-body">
                    Вы проиграли, возвращайтесь с новыми силами!
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" onclick="window.location.href='/end_game'">Exit</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
    {% if notification == 'enemy_defeated' %}
        new bootstrap.Modal(document.getElementById('enemyDefeatedModal')).show();
    {% elif notification == 'player_defeated' %}
        const modal = new bootstrap.Modal(document.getElementById('playerDefeatedModal'));
        modal.show();
        modal._element.addEventListener('hidden.bs.modal', function () {
            window.location.href = "/end_game"; // Перенаправление после закрытия
        });
    {% endif %}
});
    </script>

</body>
{% endblock %}

gameDJ/templates/end_game.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<head>
    <title>Game Over</title>
</head>
<body>
    <div class="container text-center mt-5">
        <h1 class="display-4 text-danger">Game Over</h1>
        <p class="lead">Вы хорошо держались, но потерпели поражение.</p>
        <div class="mt-4">
            <a href="/" class="btn btn-primary btn-lg">Возврат на Главную</a>
            <a href="/dashboard/" class="btn btn-success btn-lg">Повторить игру</a>
        </div>
    </div>
</body>
{% endblock %}

gameDJ/templates/home.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Infinity Battle - Главная</title>
    <link rel="stylesheet" href="{% static 'css/styles_home.css' %}">
</head>
<body>
    <div class="container">
        <h1>Добро пожаловать в <span class="highlight">Infinity battle</span>!</h1>
        <p>Это домашняя страница приложения.</p>
        {% if user.is_authenticated %}
        <a href="{% url 'infinity:dashboard' %}" class="btn">Вперёд в битву {{ username }}!</a>
        {% else %}
        <a href="{% url 'infinity:login_f' %}" class="btn">Войти в игру</a>
        {% endif %}
    </div>
</body>
{% endblock %}

gameDJ/templates/login.html
{% extends "templates/base.html" %}
{% load static %}

{% block content %}
<h2>Вход</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Вход</button>
</form>
<a href="{% url 'infinity:register' %}">Регистрация</a>
{% endblock %}

gameDJ/templates/rating.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<head>
    <title>Leaderboard</title>
</head>
<body>
    <h1>Доска почёта</h1>
    <table>
        <thead>
            <tr>
                <th>Место </th>
                <th>Игроки</th>
                <th>Лучший результат</th>
            </tr>
        </thead>
        <tbody>
            {% for player in top_players %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ player.user.username }}</td>
                <td>{{ player.high_score }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">Нет данных!</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'infinity:home' %}">домой</a>
</body>
{% endblock %}

gameDJ/templates/register.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h2>Регистрация</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Регистрация</button>
</form>
<a href="{% url 'infinity:login_f' %}">Вход</a>
{% endblock %}